apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgs-www-ingress
spec:
  defaultBackend:
    service:
      name: pegasus-ui-service
      port:
        number: 80
  rules:
    - host: sylveron.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pegasus-ui-service
                port:
                  number: 80
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pgs-sonar-ingress
spec:
  defaultBackend:
    service:
      name: sonarqube-sonarqube
      port:
        number: 9000
  rules:
    - host: sylveron.com
      http:
        paths:
          - path: /sonar
            pathType: Prefix
            backend:
              service:
                name: sonarqube-sonarqube
                port:
                  number: 9000